// Code generated by ak-ops/tools/contractgen; DO NOT EDIT.

package governance

// ClaimDefinition defines an immutable architecture claim, classification, and validation proof.
type ClaimDefinition struct {
	ClaimID               string `json:"claim_id"`
	Claim                 string `json:"claim"`
	Classification        string `json:"classification"`
	AuthoritativeEvidence string `json:"authoritative_evidence"`
	EvidenceResult        string `json:"evidence_result"`
	Correction            string `json:"correction"`
}

var canonicalClaims = []ClaimDefinition{
	{
		ClaimID:               "CLM-001",
		Claim:                 "Engine deterministic deep evaluation exists",
		Classification:        "CODE_BACKED_AND_TESTED",
		AuthoritativeEvidence: "ak-engine@c926cad internal/app/evaluate_candidate_deep.go:627-773,1534-1589 plus app tests",
		EvidenceResult:        "PROVES_NARROW_CLAIM",
		Correction:            "Research classification only.",
	},
	{
		ClaimID:               "CLM-002",
		Claim:                 "validated_research_lead is the last trustworthy boundary",
		Classification:        "CODE_BACKED_AND_TESTED",
		AuthoritativeEvidence: "ak-engine@c926cad evaluate_candidate_deep.go:763-773,1569-1589; bridge call begins 352/440",
		EvidenceResult:        "PROVES_NARROW_CLAIM",
		Correction:            "Trust stops before EvaluateAndEmit.",
	},
	{
		ClaimID:               "CLM-003",
		Claim:                 "Engine-to-RIF promotion authority is trustworthy",
		Classification:        "PARTIAL_OR_UNSAFE_IMPLEMENTATION",
		AuthoritativeEvidence: "ak-engine@c926cad adapter.go:29-166 and placeholder production calls",
		EvidenceResult:        "CONTRADICTS_CLAIM",
		Correction:            "Producer-controlled artifact is research-only.",
	},
	{
		ClaimID:               "CLM-004",
		Claim:                 "RIF independently accepts Engine evidence",
		Classification:        "INTERFACE_OR_SCAFFOLDING_ONLY",
		AuthoritativeEvidence: "ak-rif@7a6365a rif.go and complete Go tree",
		EvidenceResult:        "CONTRADICTS_CLAIM",
		Correction:            "No acceptance consumer exists.",
	},
	{
		ClaimID:               "CLM-005",
		Claim:                 "RIF has durable freeze authority",
		Classification:        "INTERFACE_OR_SCAFFOLDING_ONLY",
		AuthoritativeEvidence: "ak-rif@7a6365a registry/dataset.go and lifecycle/candidate.go",
		EvidenceResult:        "CONTRADICTS_CLAIM",
		Correction:            "Only memory mutation/scaffolding exists.",
	},
	{
		ClaimID:               "CLM-006",
		Claim:                 "Paper eligibility is implemented safely",
		Classification:        "PARTIAL_OR_UNSAFE_IMPLEMENTATION",
		AuthoritativeEvidence: "ak-rif@7a6365a core/types.go:37-55; lifecycle/candidate.go:31-58",
		EvidenceResult:        "CONTRADICTS_CLAIM",
		Correction:            "String state trusts producer boolean and is not durable.",
	},
	{
		ClaimID:               "CLM-007",
		Claim:                 "Historian hashes dataset objects",
		Classification:        "CODE_BACKED_AND_TESTED",
		AuthoritativeEvidence: "ak-historian@0c0bf4f manifest/builder.go:120-171,263-290 and tests",
		EvidenceResult:        "PROVES_NARROW_CLAIM",
		Correction:            "Local identity only; not independent RIF acceptance.",
	},
	{
		ClaimID:               "CLM-008",
		Claim:                 "Historian proves full PIT window and archive",
		Classification:        "PARTIAL_OR_UNSAFE_IMPLEMENTATION",
		AuthoritativeEvidence: "ak-historian@0c0bf4f pitcoverage/builder.go/evaluate.go; coverage/auditor.go",
		EvidenceResult:        "CONTRADICTS_BROAD_CLAIM",
		Correction:            "Snapshot unused; optional inputs; partial-window pass.",
	},
	{
		ClaimID:               "CLM-009",
		Claim:                 "Cross-repository canonical hashing exists",
		Classification:        "NOT_FOUND",
		AuthoritativeEvidence: "Engine/RIF/Historian serializers and tests",
		EvidenceResult:        "MISSING",
		Correction:            "Design supplied; implementation pending.",
	},
	{
		ClaimID:               "CLM-010",
		Claim:                 "paperfeed is recoverable",
		Classification:        "LOST_UNTRACKED_IMPLEMENTATION",
		AuthoritativeEvidence: "cleanup log 13969-13972 and forced removal 15383-15385; no preserved path/ref",
		EvidenceResult:        "CONTRADICTS_RECOVERABILITY",
		Correction:            "Untracked path existed and was lost.",
	},
	{
		ClaimID:               "CLM-011",
		Claim:                 "paperdecision is recoverable",
		Classification:        "LOST_UNTRACKED_IMPLEMENTATION",
		AuthoritativeEvidence: "cleanup log 13888-13892 and forced removal 15380-15382; no preserved path/ref",
		EvidenceResult:        "CONTRADICTS_RECOVERABILITY",
		Correction:            "Untracked path existed and was lost.",
	},
	{
		ClaimID:               "CLM-012",
		Claim:                 "ak-paper-run is recoverable",
		Classification:        "LOST_UNTRACKED_IMPLEMENTATION",
		AuthoritativeEvidence: "cleanup log 14007-14012 and forced removal 15392-15394; no preserved path/ref",
		EvidenceResult:        "CONTRADICTS_RECOVERABILITY",
		Correction:            "Untracked path existed and was lost.",
	},
	{
		ClaimID:               "CLM-013",
		Claim:                 "PaperBroker exists and passed tests",
		Classification:        "REPORT_ONLY_CLAIM",
		AuthoritativeEvidence: "ak-ops docs/progress.md:23; no preserved source/tests",
		EvidenceResult:        "INSUFFICIENT",
		Correction:            "Do not claim existence, compilation, completeness, or safety.",
	},
	{
		ClaimID:               "CLM-014",
		Claim:                 "V00Evaluator exists and passed tests",
		Classification:        "REPORT_ONLY_CLAIM",
		AuthoritativeEvidence: "ak-ops docs/progress.md:22; no preserved source/tests",
		EvidenceResult:        "INSUFFICIENT",
		Correction:            "Do not claim existence, compilation, completeness, or safety.",
	},
	{
		ClaimID:               "CLM-015",
		Claim:                 "Trader receipts/ledger/reconciliation are durable",
		Classification:        "REPORT_ONLY_CLAIM",
		AuthoritativeEvidence: "ak-ops docs/progress.md:23-26; no preserved source/tests",
		EvidenceResult:        "INSUFFICIENT",
		Correction:            "Paper workflow remains blocked.",
	},
	{
		ClaimID:               "CLM-016",
		Claim:                 "Complete paper workflow passed soak",
		Classification:        "REPORT_ONLY_CLAIM",
		AuthoritativeEvidence: "ak-ops docs/progress.md:26; no recoverable corpus/runtime",
		EvidenceResult:        "INSUFFICIENT",
		Correction:            "Historical report only.",
	},
	{
		ClaimID:               "CLM-017",
		Claim:                 "Testnet readiness exists",
		Classification:        "NOT_FOUND",
		AuthoritativeEvidence: "Current repository source and review inventory",
		EvidenceResult:        "MISSING",
		Correction:            "Testnet remains blocked and is not next.",
	},
	{
		ClaimID:               "CLM-018",
		Claim:                 "Git bundles preserved untracked paper code",
		Classification:        "REPORT_ONLY_CLAIM",
		AuthoritativeEvidence: "cleanup bundles plus cleanup status/removal log",
		EvidenceResult:        "CONTRADICTS_CLAIM",
		Correction:            "Bundles preserve Git objects, not untracked/unstaged files.",
	},
	{
		ClaimID:               "CLM-019",
		Claim:                 "AK_PAPER_INTEGRATION_NOT_FOUND",
		Classification:        "NOT_FOUND",
		AuthoritativeEvidence: "All-ref/path/content searches; recovery review; archive entry search",
		EvidenceResult:        "PROVEN",
		Correction:            "No complete paper integration recoverable.",
	},
	{
		ClaimID:               "CLM-020",
		Claim:                 "CLEANUP_LOSS_PROVEN",
		Classification:        "LOST_UNTRACKED_IMPLEMENTATION",
		AuthoritativeEvidence: "cleanup execution log status and force removal lines",
		EvidenceResult:        "PROVEN",
		Correction:            "Exact contents and quality remain unknowable.",
	},
}

// AllClaims returns all canonical architecture claims.
func AllClaims() []ClaimDefinition {
	copied := make([]ClaimDefinition, len(canonicalClaims))
	copy(copied, canonicalClaims)
	return copied
}

// LookupClaim retrieves a claim definition by ID.
func LookupClaim(claimID string) (ClaimDefinition, bool) {
	for _, c := range canonicalClaims {
		if c.ClaimID == claimID {
			return c, true
		}
	}
	return ClaimDefinition{}, false
}
